name: Render PlantUML Diagrams

on:
  push:
    paths:
      - '**/*.puml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PlantUML
        run: |
          sudo apt-get install -y graphviz
          pip install plantuml-markdown

      - name: Render PlantUML diagrams
        run: plantuml-markdown '**/*.puml'
